name: Build and deploy Python project to Azure Function App - data-entry-app-backend

on:
  push:
    branches:
      - function-web-app
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend/azure' # <-- Set to your function app directory
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      # Optional: Add step to run tests here

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F8A6AB7692D74E62851BB2B5DAD0F438 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D74B7BB9CBEB432F92186128FBE8A912 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7FCA0247D269459EBE3C832E3B570F20 }}

      - name: Publish Function App with Core Tools
        run: func azure functionapp publish data-entry-app-backend --python
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
